### ISSUE TITLE
Unit Test Fails on more than 2 Team

### ISSUE THREAD

**Issue by themazim** [moserware/PHPSkills#10]
sh-4.2$ php phpunit.phar src/Moserware/UnitTests/TrueSkill/FactorGraphTeamTrueSkillCalculatorTest.php
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ming.ini on line 1 in Unknown on line 0
PHPUnit 4.7.6 by Sebastian Bergmann and contributors.

PHP Fatal error:  Class 'Moserware\Skills\TrueSkill\Layers\InvalidOperationException' not found in /var/www/test/PHPSkills/src/Moserware/Skills/TrueSkill/Layers/IteratedTeamDifferencesInnerLayer.php on line 55

Would love to use this, unfortunately Unit Tests fails with exception

**Comment by lpeabody** [comment]
I'm also running into this.

**Comment by moserware** [comment]
I no longer run PHP. I'd be happy to accept pull requests on this

**Comment by lpeabody** [comment]
@moserware I opened pull request #11, the details of which can be viewed there, but my PR does take care of this issue with `InvalidOperationException`. All existing tests either produce an error, pass, or fail; no tests crash.

**Comment by Zn4rK** [comment]
This should be solved by https://github.com/moserware/PHPSkills/pull/12

Feel free to reopen this issue if you still are experiencing problems!
