### ISSUE TITLE
Runtime Notice for variable by &$reference

### ISSUE THREAD

**Issue by bartrail** [moserware/PHPSkills#2]
Thanks again for these beautiful maths!

I got into trouble with a strict PHP configuration, saying "Runtime Notice: Only variables should be assigned by reference in /home/con/www/lab/Moserware/Skills/HashMap.php line 36 "

When I disable the strict mode (or at least disable notices in php's error_reporting()) it works and I get a calculation. Unfortunately, I need the  strict mode and all notices for the development to easier find bugs and the framework I'm using (Symfony2) even throws full Exceptions on notices (thanks to xdebug) so I can't even ignore a notice, even though I'd like to.

So I was trying to get rid of all ampersands as I don't fully understand the php 5.3 runtime notice for references - thought anything is a reference by now.. - seems it is not.. so unfortunately I broke the whole environment and some unit tests are totally going nuts.. 

Maybe you find some time to take a look over this, this is the commit where I radiacally (blindly, but not search & replace ;) removed the ampersands
https://github.com/bartrail/PHPSkills/commit/c61ca4e52d95411c7f7023a06f47518acf9f2c6b

and this is one of the tests that failed and I was trying to manually find out which else is failing in this TwoTeam Test case (came out this was it) - so I revered the unit test values in my fork back to the original ones, but maybe this can help you to locate which ampersand &reference is really needed...
https://github.com/bartrail/PHPSkills/commit/389665e091975229ea1a8696f6c3c2be9839b73b

Cheers,
Conrad

**Comment by Zn4rK** [comment]
This should be solved by https://github.com/moserware/PHPSkills/pull/12

Feel free to reopen this issue if you still are experiencing problems!
