### ISSUE TITLE
Error On calculateMatchQuality

### ISSUE THREAD

**Issue by pkirk** [moserware/PHPSkills#4]
Looking at the paper's PDF
http://research.microsoft.com/pubs/67956/NIPS2006_0688.pdf (equation 7)
you swapped Sigma with Mu

This line below:
($totalPlayers*$betaSquared + $team1StdDevSquared + $team2SigmaSquared)
should be:
($totalPlayers*$betaSquared + $team1StdDevSquared + $team2StdDevSquared)

and so the "exp" part has a mirror error.

**Comment by Zn4rK** [comment]
This should be solved by https://github.com/moserware/PHPSkills/pull/12

Feel free to reopen this issue if you still are experiencing problems!
